### ISSUE TITLE
[Idea] Choose number of days to view

### ISSUE THREAD

**Issue by robertybob** [szech/mmm-uk-pollen-forecast#1]
Hi! As someone who has suffered terribly with hayfever during lockdown, I'm loving this module! I'm wondering if it would be possible to only show today, or next X days?

Also, do you have a contact email address? I've an idea for a module for us Brits but I've got 0 coding skills whatsoever.

**Comment by szech** [comment]
Hi! Happy that you found this useful.
Can't believe I was the first one to publish this sort of thing.


It should be fairly easy to configure the number of days. I will try to
investigate this week.

(It may also be possible to do with just css on your local installation,
with no code changes, if you want a little coding challenge for yourself)

**Comment by szech** [comment]
hi @robertybob, the latest update addresses this.
please update your local installation and config and report back. 
(the mirror may need to be restarted to pick up the changes)

**Comment by robertybob** [comment]
@szech  Thank you for implementing this!

**Comment by szech** [comment]
yay! 😄
