### ISSUE TITLE
[Issue] Icons not centred when on the right hand side of the screen.

### ISSUE THREAD

**Issue by carlywarly** [szech/mmm-uk-pollen-forecast#2]
My wife loves this module, she has almost forgiven me for building a MM in the first place :)

We noticed that the letters in the coloured icons where not centred when we moved the module to the right hand size (bottom_right).

Hope you don't mind but the easiest way I found to fix this, was adding **text-align: center;** to .icon section of the CSS.

.icon {
    color: black;
    display: inline-block;
    font-style: normal;
    height: 2.5em;
    margin: 0 auto;
    overflow: hidden;
    text-indent: 0px;
    white-space: nowrap;
    width: 2.5em;
    border-radius: 50%;
    text-align: center;
}

BTW may thanks for the module @szech 

Carl

**Comment by szech** [comment]
Thanks for commenting! Glad you like the module.
Will look at incorporating your change soon 👍

**Comment by carlywarly** [comment]
Hi @szech,  think I found a better solution. If we add

.pollen-container td {
  text-align: center;
} 

to pollen-container.css, it centres the days as well.

Carl

**Comment by szech** [comment]
hi @carlywarly, the latest update addresses this.
please update your local installation and config and report back.

**Comment by carlywarly** [comment]
perfect, again many thanks :)

Carl
