### ISSUE TITLE
[Idea] Icons only

### ISSUE THREAD

**Issue by carlywarly** [szech/mmm-uk-pollen-forecast#3]
I would also like to add the option to display the coloured icons only and not the forecast text.  My wife just wants to know how miserable it's going to be and not really "bothered" why :) 

I added the below to mmm-uk-pollen-forecast.js
    defaults: {
        IconsOnly: false, // only display icons 
        ...
    },

and changed the line
                    const html_dump = forecast_heading + forecast_table + forecast_text + forecast_issued ;
to
                if (payload.config.IconsOnly) {
                    var html_dump = forecast_heading + forecast_table + forecast_issued;                
                } else {
                    var html_dump = forecast_heading + forecast_table + forecast_text + forecast_issued ;
                }

in node_helper.js

![image](https://user-images.githubusercontent.com/50866001/88724511-89d8c700-d122-11ea-8ad5-00a41e3f364b.png)

Again, thanks @szech for an awesome module.

Carl

**Comment by szech** [comment]
Agreed, it's good to have options.

**Comment by szech** [comment]
hi @carlywarly, the latest update addresses this.
please update your local installation and config and report back.
(the mirror may need to be restarted to pick up the changes)

**Comment by carlywarly** [comment]
perfect, again many thanks :)

Carl
